name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  baseUrl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: './'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLITOOLS_BATCH_ID: ${{ github.sha }}
        appName: 'Applitools Eyes Action'
        batchName: 'BodilessDemo'
        baseUrl: https://main-bvxea6i-vadijmmtl4ax4.us-4.platformsh.site/
        # ignoreSelector: '.article-list'
        # showLogs: true

  # sitemapUrl:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: './'
  #     with:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       APPLITOOLS_BATCH_ID: ${{ github.sha }}
  #       appName: 'Applitools Eyes Action'
  #       batchName: 'Next.js WordPress Starter'
  #       sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml

  # concurrency:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: './'
  #     with:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       APPLITOOLS_BATCH_ID: ${{ github.sha }}
  #       appName: 'Applitools Eyes Action'
  #       batchName: 'Next.js WordPress Starter'
  #       sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml
  #       concurrency: 20