name: Test

on: [pull_request]

env:
  DEPLOY_HOST: "spontaneous-sable-dfb1f0.netlify.app"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Wait for Netlify Deploy
      uses: probablyup/wait-for-netlify-action@3.2.0
      id: waitForDeployment
      with:
        site_id: 'd2029b83-4181-4472-ab3a-c5d753828ee4' # See Settings > Site Details > General in the Netlify UI
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
    
    - name: Storing Preview URL in Environment
      run: echo "DEPLOY_HOST=deploy-preview-${{ github.event.pull_request.number }}--${{ env.DEPLOY_HOST }}" >> $GITHUB_ENV

    - uses: colbyfayock/applitools-eyes-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        APPLITOOLS_BATCH_ID: ${{ github.sha }}
        appName: BodilessTest
        baseUrl: "https://spontaneous-sable-dfb1f0.netlify.app/"
        maxDepth: 2
        concurrency: 3